const errors = {
  REQUIRED_FIELD: 'REQUIRED_FIELD',
  MIN_FIELD_LENGTH: 'MIN_FIELD_LENGTH',
  MAX_FIELD_LENGTH: 'MAX_FIELD_LENGTH',
  NOT_UNIQUE_DATA: 'NOT_UNIQUE_DATA',
  NOT_VALID_DATA: 'NOT_VALID_DATA',
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_URL: 'INVALID_URL',
  CONFLICT_ERROR: 'CONFLICT_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  UNAUTHORIZED: 'UNAUTHORIZED',
  SERVERERROR: 'SERVERERROR',
  EMPTY_FIELD: 'EMPTY_FIELD',
  NOT_STRING: 'NOT_STRING',
  CONFLICT_EMAIL: 'CONFLICT_EMAIL',
  INVALID_ID: 'INVALID_ID',
};
module.exports = errors;
